/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`tests/documentation-routes.test.js TAP Test Fastify creation with custom prefix > must match snapshot 1`] = `
{"openapi":"3.0.3","info":{"title":"Example application","description":"This application is an example for the lc39 functionality","version":"TEST_VERSION"},"components":{"schemas":{"def-0":{"type":"string","enum":["foo","bar"],"title":"foobar"}}},"paths":{"/prefix//":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/error":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/wrong-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/empty-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/items/{itemId}":{"get":{"responses":{"200":{"description":"Default Response"}}},"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-schema":{"post":{"responses":{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"foobar":{"type":"string","enum":["foo","bar"]}}}}}}}}},"/prefix/with-logs":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-logs-uppercase":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-error-logs":{"get":{"responses":{"200":{"description":"Default Response"}}}}}}
`

exports[`tests/documentation-routes.test.js TAP Test Fastify creation with custom prefix without trailing slash > must match snapshot 1`] = `
{"openapi":"3.0.3","info":{"title":"Example application","description":"This application is an example for the lc39 functionality","version":"TEST_VERSION"},"components":{"schemas":{"def-0":{"type":"string","enum":["foo","bar"],"title":"foobar"}}},"paths":{"/prefix/":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/error":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/wrong-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/empty-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/items/{itemId}":{"get":{"responses":{"200":{"description":"Default Response"}}},"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-schema":{"post":{"responses":{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"foobar":{"type":"string","enum":["foo","bar"]}}}}}}}}},"/prefix/with-logs":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-logs-uppercase":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/prefix/with-error-logs":{"get":{"responses":{"200":{"description":"Default Response"}}}}}}
`

exports[`tests/documentation-routes.test.js TAP Test Fastify creation with no prefix > must match snapshot 1`] = `
{"openapi":"3.0.3","info":{"title":"Example application","description":"This application is an example for the lc39 functionality","version":"TEST_VERSION"},"components":{"schemas":{"def-0":{"type":"string","enum":["foo","bar"],"title":"foobar"}}},"paths":{"/":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/error":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/wrong-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/empty-content-length":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/items/{itemId}":{"get":{"responses":{"200":{"description":"Default Response"}}},"post":{"responses":{"200":{"description":"Default Response"}}}},"/with-schema":{"post":{"responses":{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"foobar":{"type":"string","enum":["foo","bar"]}}}}}}}}},"/with-logs":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/with-logs-uppercase":{"post":{"responses":{"200":{"description":"Default Response"}}}},"/with-error-logs":{"get":{"responses":{"200":{"description":"Default Response"}}}}}}
`
